### ISSUE TITLE
Vector appending not supported

### ISSUE THREAD

**Issue by mterber** [mterber/ceu-editor#20] opened 2016-05-31 13:48 UTC
<pre><code>var u8[10] f;
f = [] .. f .. [5]; // '..' notation leads to syntax errors
</code></pre>

**Comment by langej** [comment] 2016-06-07 08:00
caused by #23

**Comment by langej** [comment] 2016-06-09 08:38
https://www.eclipse.org/forums/index.php/t/1078237/

**Comment by langej** [comment] 2016-06-09 09:47
fixed with 1fb429637b0917658b52b754e65d0525c8950f8f

**Closed as completed by langej** 2016-06-09 09:47 UTC
Labels: bug, Priority-High
